# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'ObjectMapper'
   pod 'AnimatedField'
   pod 'Alamofire'
   pod 'SwiftyJSON'
   pod 'ObjectMapper'
   pod 'AlamofireImage', '~> 3.5'
   pod 'SVProgressHUD'
   pod 'SwiftyGif'
end
